stages:
  - deploy

publish:
  stage: deploy
  environment:
    name: production
  only:
    - tags
  tags:
    - chef
  script:
    - /usr/local/bin/deploy-publish.sh $DEPLOY_HOST $DEPLOY_PATH $CI_COMMIT_TAG
